name = "FourMomentumBase"
uuid = "592a752d-6533-4762-a71b-738712ea30ec"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de"]
version = "0.0.1-DEV"

[deps]

[compat]
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random","SafeTestsets"]

